gym_env: blokus_gym:blokus-simple-v0
experiment_name: blokus
wanda: false
wandb_project_name: sandboxRL
capture_video: false
cuda: false
dropout: 0.1
d_model: 256
num_steps: 32
learning_rate: 1.0e-5
max_grad_norm: 0.5
detect_anomaly: true
log_level: "DEBUG"
