gym_env: blokus_gym:blokus-simple-v0
experiment_name: ppo_blokus_7x7
log_dir: models/logs/ppo_blokus_7x7
checkpoint_dir: models/checkpoints/ppo_blokus_7x7
agent_type: "cnn"
save_interval: 500
wanda: false
capture_video: false
cuda: true
dropout: 0.1
d_model: 128
num_steps: 32
learning_rate: 1.0e-5
max_grad_norm: 0.5
