name: Python code analysis

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    pylint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'
                  architecture: 'x64'
            - name: Install Cython
              run: |
                    python -m pip install --upgrade pip
                    pip install Cython==3.0.3
            - name: Install dependencies
              run: |
                    pip install -e .
            - name: Run pylint
              run: |
                  pylint --rcfile pyproject.toml blokus_rl/
    pycodestyle:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'
                  architecture: 'x64'
            - name: Install Cython
              run: |
                    python -m pip install --upgrade pip
                    pip install Cython==3.0.3
            - name: Install dependencies
              run: |
                    pip install -e .
            - name: Run pycodestyle
              run: |
                  pycodestyle --max-line-length 120 blokus_rl/
    mypy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'
                  architecture: 'x64'
            - name: Install Cython
              run: |
                    python -m pip install --upgrade pip
                    pip install Cython==3.0.3
            - name: Install dependencies
              run: |
                    pip install -e .
            - name: Run pycodestyle
              run: |
                  mypy --ignore-missing-imports blokus_rl/
